#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'flumereportserver_types'


module FlumeNodeState
  HELLO = 0
  IDLE = 1
  CONFIGURING = 2
  ACTIVE = 3
  ERROR = 4
  LOST = 5
  DECOMMISSIONED = 6
  CLOSING = 7
  VALUE_MAP = {0 => "HELLO", 1 => "IDLE", 2 => "CONFIGURING", 3 => "ACTIVE", 4 => "ERROR", 5 => "LOST", 6 => "DECOMMISSIONED", 7 => "CLOSING"}
  VALID_VALUES = Set.new([HELLO, IDLE, CONFIGURING, ACTIVE, ERROR, LOST, DECOMMISSIONED, CLOSING]).freeze
end

class ThriftFlumeConfigData
  include ::Thrift::Struct, ::Thrift::Struct_Union
  TIMESTAMP = 1
  SOURCECONFIG = 2
  SINKCONFIG = 3
  SOURCEVERSION = 4
  SINKVERSION = 5
  FLOWID = 6

  FIELDS = {
    TIMESTAMP => {:type => ::Thrift::Types::I64, :name => 'timestamp'},
    SOURCECONFIG => {:type => ::Thrift::Types::STRING, :name => 'sourceConfig'},
    SINKCONFIG => {:type => ::Thrift::Types::STRING, :name => 'sinkConfig'},
    SOURCEVERSION => {:type => ::Thrift::Types::I64, :name => 'sourceVersion'},
    SINKVERSION => {:type => ::Thrift::Types::I64, :name => 'sinkVersion'},
    FLOWID => {:type => ::Thrift::Types::STRING, :name => 'flowID'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

