#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


class ThriftFlumeReport
  include ::Thrift::Struct, ::Thrift::Struct_Union
  STRINGMETRICS = 3
  LONGMETRICS = 4
  DOUBLEMETRICS = 5

  FIELDS = {
    STRINGMETRICS => {:type => ::Thrift::Types::MAP, :name => 'stringMetrics', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRING}},
    LONGMETRICS => {:type => ::Thrift::Types::MAP, :name => 'longMetrics', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::I64}},
    DOUBLEMETRICS => {:type => ::Thrift::Types::MAP, :name => 'doubleMetrics', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::DOUBLE}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

